openapi: "3.0.1"
info:
  title: "Rust Axum+SeaORM Sample"
  description: ""
  version: 0.0.1
servers:
  - url: http://localhost:8085
tags:
  - name: user
  - name: post
paths:
  "/users":
    $ref: "./paths/users/index.yaml"
  "/users/{id}":
    $ref: "./paths/users/_id.yaml"
components:
  schemas:
    "User":
      $ref: "./schemas/user.yaml#/User"
